[package]
name = "rivet-bsp-support"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Rivet RTOS: shared helpers for rivet-bsp-* crates (software watchdog, NS16550 UART)"

[dependencies]
rivet = { path = "../rivet", version = "0.2.0", package = "rivet-rtos" }
embedded-hal = "1.0"
embedded-hal-async = "1.0"
embedded-hal-nb = "1.0"
nb = "1.1"

[lib]
