//! Compile-time kernel configuration (plan.md §4.1).
//!
//! Generated by `build.rs` from the `RIVET_*` environment variables; see
//! `rivet/build.rs` for the full list and defaults. The whole kernel sizes
//! itself from these constants — every array is `[T; MAX_*]`.

include!(concat!(env!("OUT_DIR"), "/config.rs"));
